spring:
  datasource:
    url: jdbc:mysql://localhost:3306/music_app
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true

    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
